### PR TITLE
Fix rendering markdown tables. Fixes #46

### LINKED ISSUE #46: Tables are not rendered
image

https://marketplace.visualstudio.com/items/pflannery.vscode-versionlens/changelog
https://gitlab.com/versionlens/vscode-versionlens/-/blob/master/CHANGELOG.md#anchor-140

### PR DESCRIPTION
**Pull request by jerone**
image

### CODE REVIEW

File: src/test/helpers/extension-data.ts [hunk 1]
```diff
@@ -7,7 +7,12 @@ export const EXTENSION_METADATA = [
   {
     id: 'ID_1',
     extensionPath: 'PATH_1',
-    packageJSON: {displayName: 'My Extension 1', version: '1.0.0', homepage: 'https://github.com/ryu1kn/vscode-extension-update-reporter'}
+    packageJSON: {
+      displayName: 'My Extension 1',
+      version: '1.0.0',
+      homepage: 'https://github.com/ryu1kn/vscode-extension-update-reporter',
+      repository: 'https://github.com/ryu1kn/vscode-extension-update-reporter.git'
```
Comment (jerone) [inline src/test/helpers/extension-data.ts:14]: This change is not related to this PR, but still very useful.

**Comment by ryu1kn** [comment]
👍
